# Generated by Django 3.2.4 on 2021-06-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Nom',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.CharField(default='adresse', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_doctorant',
            field=models.BooleanField(default=False, verbose_name='doctorant status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='enseignant status'),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(default='prenom', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='tel', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
