# Generated by Django 3.2.4 on 2021-06-13 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esiapp', '0002_auto_20210613_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=60)),
                ('description_categorie', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('send_By', models.CharField(max_length=255)),
                ('date_ajout', models.DateField(auto_now=True)),
                ('date_limite', models.DateField()),
                ('etat_publication', models.BooleanField(default=False)),
                ('priorite_contenu', models.CharField(blank=True, choices=[('priorite 1', 'priorite 1'), ('priorite 2', 'priorite 2'), ('priorite 3', 'priorite 3')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationFicher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('path_fichier', models.FileField(blank=True, null=True, upload_to='files/')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esiapp.publication')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire_msg', models.CharField(max_length=255)),
                ('date_ajout', models.DateField(auto_now=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esiapp.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
