# Generated by Django 3.2.4 on 2021-06-13 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esiapp', '0003_category_commentaire_publication_publicationficher'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='Categorie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='esiapp.category'),
        ),
    ]
