# Generated by Django 3.2.4 on 2021-06-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esiapp', '0004_publication_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='commentaire_msg',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='message',
            field=models.TextField(),
        ),
    ]
