# Generated by Django 3.2.4 on 2021-06-14 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esiapp', '0006_auto_20210614_0100'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
