# Generated by Django 3.2.4 on 2021-06-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esiapp', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date_ajout',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
