wilayas = (
    ('Adrar', 'Adrar'),
    ('Chlef', 'Chlef'),
    ('Laghouat', 'Laghouat'),
    ('Oum El Bouaghi', 'Oum El Bouaghi'),
    ('Batna', 'Batna'),
    ('Béjaïa', 'Béjaïa'),
    ('Biskra', 'Biskra'),
    ('Béchar', 'Béchar'),
    ('Blida', 'Blida'),
    ('Bouïra', 'Bouïra'),
    ('Tamanrasset', 'Tamanrasset'),
    ('Tébessa', 'Tébessa'),
    ('Tlemcen', 'Tlemcen'),
    ('Tiaret', 'Tiaret'),
    ('Tizi Ouzou', 'Tizi Ouzou'),
    ('Alger', 'Alger'),
    ('Djelfa', 'Djelfa'),
    ('Jijel', 'Jijel'),
    ('Sétif', 'Sétif'),
    ('Saïda', 'Saïda'),
    ('Skikda', 'Skikda'),
    ('Sidi Bel Abbès', 'Sidi Bel Abbès'),
    ('Annaba', 'Annaba'),
    ('Guelma', 'Guelma'),
    ('Constantine', 'Constantine'),
    ('Médéa', 'Médéa'),
    ('Mostaganem', 'Mostaganem'),
    ('M\'Sila', 'M\'Sila'),
    ('Mascara', 'Mascara'),
    ('Ouargla', 'Ouargla'),
    ('Oran', 'Oran'),
    ('El Bayadh', 'El Bayadh'),
    ('Illizi', 'Illizi'),
    ('Bordj Bou Arréridj', 'Bordj Bou Arréridj'),
    ('Boumerdès', 'Boumerdès'),
    ('El Tarf', 'El Tarf'),
    ('Tindouf', 'Tindouf'),
    ('Tissemsilt', 'Tissemsilt'),
    ('El Oued', 'El Oued'),
    ('Khenchela', 'Khenchela'),
    ('Souk Ahras', 'Souk Ahras'),
    ('Tipaza', 'Tipaza'),
    ('Mila', 'Mila'),
    ('Aïn Defla', 'Aïn Defla'),
    ('Naâma', 'Naâma'),
    ('Aïn Témouchent', 'Aïn Témouchent'),
    ('Ghardaïa', 'Ghardaïa'),
    ('Relizane', 'Relizane'),
    ('El M\'ghair', 'El M\'ghair'),
    ('El Menia', 'El Menia'),
    ('Ouled Djellal', 'Ouled Djellal'),
    ('Bordj Baji Mokhtar', 'Bordj Baji Mokhtar'),
    ('Béni Abbès', 'Béni Abbès'),
    ('Timimoun', 'Timimoun'),
    ('Touggourt', 'Touggourt'),
    ('Djanet', 'Djanet'),
    ('In Salah', 'In Salah'),
    ('In Guezzam', 'In Guezzam'),
)

universities = (
    ('Université de Béchar - Mohamed Tahri', 'Université de Béchar - Mohamed Tahri'),
    ('Université  de Mascara - Mustapha Stambouli', 'Université  de Mascara - Mustapha Stambouli'),
    ('Université de Saida - Tahar Moulay ', 'Université de Saida - Tahar Moulay '),
    ('Université  de Tlemcen - Abou Bekr Belkaid ', 'Université  de Tlemcen - Abou Bekr Belkaid '),
    ('Université  d\'Adrar - Ahmed Draya ', 'Université  d\'Adrar - Ahmed Draya '),
    ('Université  de Bouira - Akli Mohand Oulhadj', 'Université  de Bouira - Akli Mohand Oulhadj'),
    ('Université  de Djelfa - Ziane Achour ', 'Université  de Djelfa - Ziane Achour '),
    ('Université de Ghardaia ', 'Université de Ghardaia '),
    ('Université  de Khemis Miliana - Djilali Bounaama ', 'Université  de Khemis Miliana - Djilali Bounaama '),
    ('Université  Médéa - Yahia Farès ', 'Université  Médéa - Yahia Farès '),
    ('Université  de Jijel - Mohammed Seddik Ben yahia ', 'Université  de Jijel - Mohammed Seddik Ben yahia '),
    ('Université de Tébessa - Larbi Tébessi ', 'Université de Tébessa - Larbi Tébessi '),
    ('Université de Bordj Bou Arréridj - Mohamed Bachir El Ibrahimi ',
     'Université de Bordj Bou Arréridj - Mohamed Bachir El Ibrahimi '),
    ('Université  de Constantine 1 - Frères Mentouri ', 'Université  de Constantine 1 - Frères Mentouri '),
    ('Université  de Constantine 2 - Abdelhamid Mehri ', 'Université  de Constantine 2 - Abdelhamid Mehri '),
)
